package seed

// HarvestInstruction represents an instruction for the Narration Agent to plant
// a Global Seed clue in the narrative.
//
// Design Philosophy:
//   - Generated by SeedManager.CheckHarvest() during game loop
//   - Passed to Narration Agent to ensure clues are woven into narrative
//   - Priority determines order of revelation when multiple clues are available
//   - Keywords and MustInclude guide narrative generation to ensure coherence
type HarvestInstruction struct {
	SeedID      string   `json:"seed_id"`       // ID of the Global Seed (e.g., "GS001")
	ClueContent string   `json:"clue_content"`  // The clue text to reveal
	Keywords    []string `json:"keywords"`      // Keywords that must be echoed in narration
	MustInclude string   `json:"must_include"`  // Essential narrative elements to include
	Priority    int      `json:"priority"`      // Priority score (higher = more urgent)
	Tier        int      `json:"tier"`          // Current tier being revealed (1-3)
}

// NewHarvestInstruction creates a new HarvestInstruction from a Global Seed.
//
// Parameters:
//   - seed: The GlobalSeed to create instruction from
//   - currentBeat: The current game beat number
//
// Returns:
//   - *HarvestInstruction: A new harvest instruction with calculated priority
//   - error: If the seed is not ready to reveal at current beat
func NewHarvestInstruction(seed *GlobalSeed, currentBeat int) (*HarvestInstruction, error) {
	// Check if fully revealed first (more specific error)
	clue := seed.GetCurrentClue()
	if clue == nil {
		return nil, ErrNoClueAvailable
	}

	if !seed.IsReadyToReveal(currentBeat) {
		return nil, ErrSeedNotReady
	}

	priority := calculatePriority(seed, currentBeat)

	return &HarvestInstruction{
		SeedID:      seed.ID,
		ClueContent: clue.Content,
		Keywords:    clue.Keywords,
		MustInclude: seed.LinkedTruth, // Use LinkedTruth theme, not the explicit Content
		Priority:    priority,
		Tier:        seed.CurrentTier,
	}, nil
}

// calculatePriority computes the priority score for a harvest instruction.
//
// Priority Calculation Rules:
//  1. Lower CurrentTier = Higher priority (prioritize new seeds)
//     - Tier 1 seeds: +300 points
//     - Tier 2 seeds: +200 points
//     - Tier 3 seeds: +100 points
//
//  2. Closer to BeatEnd = Higher priority (avoid missing revelation window)
//     - Priority increases as beats remaining decrease
//     - Max bonus: +200 points (when 0 beats remaining)
//
//  3. More RelatedSeeds = Higher priority (advance main storyline)
//     - Each related seed: +5 points
//
// Parameters:
//   - seed: The GlobalSeed to calculate priority for
//   - currentBeat: The current game beat number
//
// Returns:
//   - int: Calculated priority score (higher = more urgent)
func calculatePriority(seed *GlobalSeed, currentBeat int) int {
	priority := 0

	// 1. Prioritize lower tiers (new seeds)
	tierBonus := (4 - seed.CurrentTier) * 100
	priority += tierBonus

	// 2. Prioritize seeds nearing end of revelation window
	clue := seed.GetCurrentClue()
	if clue != nil {
		beatsRemaining := clue.BeatEnd - currentBeat
		if beatsRemaining < 0 {
			beatsRemaining = 0
		}
		// Inverse relationship: fewer beats remaining = higher priority
		urgencyBonus := (20 - beatsRemaining) * 10
		if urgencyBonus < 0 {
			urgencyBonus = 0
		}
		priority += urgencyBonus
	}

	// 3. Prioritize seeds with more relationships (main storyline)
	relatedBonus := len(seed.RelatedSeeds) * 5
	priority += relatedBonus

	return priority
}
