package seed

import "fmt"

// Priority calculation constants (Issue #5 fix: extracted magic numbers)
const (
	// MaxTiers is the maximum number of tiers in ClueChain
	MaxTiers = 3

	// TierBonusWeight is the points awarded per tier level difference
	// Tier 1: (MaxTiers+1-1)*100 = 300 points
	// Tier 2: (MaxTiers+1-2)*100 = 200 points
	// Tier 3: (MaxTiers+1-3)*100 = 100 points
	TierBonusWeight = 100

	// UrgencyMaxBeats is the maximum beats for urgency calculation
	// Assumes game typically runs ~18-20 beats
	UrgencyMaxBeats = 20

	// UrgencyWeight is the points per beat of urgency
	// Max urgency bonus: (UrgencyMaxBeats - 0) * 10 = 200 points
	UrgencyWeight = 10

	// RelatedSeedWeight is the points per related seed
	// Encourages progression of interconnected story elements
	RelatedSeedWeight = 5
)

// HarvestInstruction represents an instruction for the Narration Agent to plant
// a Global Seed or Local Seed clue in the narrative.
//
// Design Philosophy:
//   - Generated by SeedManager.CheckHarvest() during game loop
//   - Passed to Narration Agent to ensure clues are woven into narrative
//   - Priority determines order of revelation when multiple clues are available
//   - Keywords and MustInclude guide narrative generation to ensure coherence
//   - Supports both Global Seeds (tier-based) and Local Seeds (urgency-based)
type HarvestInstruction struct {
	SeedID      string   `json:"seed_id"`       // ID of the seed (e.g., "GS001" or "LS-hospital-01")
	ClueContent string   `json:"clue_content"`  // The clue text to reveal
	Keywords    []string `json:"keywords"`      // Keywords that must be echoed in narration
	MustInclude string   `json:"must_include"`  // Essential narrative elements to include
	Priority    int      `json:"priority"`      // Priority score (higher = more urgent)
	Tier        int      `json:"tier"`          // Current tier being revealed (1-3 for Global, 0 for Local)
	IsLocalSeed bool     `json:"is_local_seed"` // True if this is a Local Seed harvest
}

// NewHarvestInstruction creates a new HarvestInstruction from a Global Seed.
//
// Parameters:
//   - seed: The GlobalSeed to create instruction from
//   - currentBeat: The current game beat number
//
// Returns:
//   - *HarvestInstruction: A new harvest instruction with calculated priority
//   - error: If the seed is not ready to reveal at current beat
func NewHarvestInstruction(seed *GlobalSeed, currentBeat int) (*HarvestInstruction, error) {
	// Check if fully revealed first (more specific error)
	clue := seed.GetCurrentClue()
	if clue == nil {
		return nil, ErrNoClueAvailable
	}

	if !seed.IsReadyToReveal(currentBeat) {
		return nil, ErrSeedNotReady
	}

	priority := calculatePriority(seed, currentBeat)

	return &HarvestInstruction{
		SeedID:      seed.ID,
		ClueContent: clue.Content,
		Keywords:    clue.Keywords,
		MustInclude: seed.LinkedTruth, // Use LinkedTruth theme, not the explicit Content
		Priority:    priority,
		Tier:        seed.CurrentTier,
	}, nil
}

// calculatePriority computes the priority score for a harvest instruction.
//
// Priority Calculation Rules (Issue #5 fix: uses constants):
//  1. Lower CurrentTier = Higher priority (prioritize new seeds)
//     - Tier 1 seeds: +300 points (MaxTiers+1-1)*TierBonusWeight
//     - Tier 2 seeds: +200 points (MaxTiers+1-2)*TierBonusWeight
//     - Tier 3 seeds: +100 points (MaxTiers+1-3)*TierBonusWeight
//
//  2. Closer to BeatEnd = Higher priority (avoid missing revelation window)
//     - Priority increases as beats remaining decrease
//     - Max bonus: +200 points (UrgencyMaxBeats * UrgencyWeight)
//
//  3. More RelatedSeeds = Higher priority (advance main storyline)
//     - Each related seed: +RelatedSeedWeight points
//
// Parameters:
//   - seed: The GlobalSeed to calculate priority for
//   - currentBeat: The current game beat number
//
// Returns:
//   - int: Calculated priority score (higher = more urgent)
func calculatePriority(seed *GlobalSeed, currentBeat int) int {
	priority := 0

	// 1. Tier bonus: Lower tier = Higher priority
	tierBonus := (MaxTiers + 1 - seed.CurrentTier) * TierBonusWeight
	priority += tierBonus

	// 2. Urgency bonus: Closer to BeatEnd = Higher priority
	clue := seed.GetCurrentClue()
	if clue != nil {
		beatsRemaining := clue.BeatEnd - currentBeat
		if beatsRemaining < 0 {
			beatsRemaining = 0
		}
		// Inverse relationship: fewer beats remaining = higher priority
		urgencyBonus := (UrgencyMaxBeats - beatsRemaining) * UrgencyWeight
		if urgencyBonus < 0 {
			urgencyBonus = 0
		}
		priority += urgencyBonus
	}

	// 3. Relationship bonus: More related seeds = Higher priority
	relatedBonus := len(seed.RelatedSeeds) * RelatedSeedWeight
	priority += relatedBonus

	return priority
}

// NewLocalSeedHarvestInstruction creates a new HarvestInstruction from a Local Seed.
//
// Priority Calculation for LocalSeeds:
//   - Priority = Urgency * 5 (simple scaling formula)
//   - Urgency 100 (expired): Priority 500 (highest priority, critical)
//   - Urgency 90 (1 beat left): Priority 450 (extremely high)
//   - Urgency 60 (2 beats left): Priority 300 (high, forced harvest threshold)
//   - Urgency 40 (3 beats left): Priority 200 (medium)
//   - Urgency 20 (4+ beats left): Priority 100 (low)
//
// This scaling ensures:
//   1. High-urgency LocalSeeds (90-100) take precedence over most GlobalSeeds
//   2. Priority range (0-500) remains compatible with GlobalSeed priorities (~100-500)
//   3. Semantic clarity: urgency (0-100) is human-readable, priority (0-500) is for sorting
//
// Parameters:
//   - seed: The LocalSeed to create instruction from
//   - currentBeat: The current game beat number
//
// Returns:
//   - *HarvestInstruction: A new harvest instruction with urgency-based priority
//   - error: If the seed is not active or has expired beyond recovery
func NewLocalSeedHarvestInstruction(seed *LocalSeed, currentBeat int) (*HarvestInstruction, error) {
	// Validate inputs
	if seed == nil {
		return nil, fmt.Errorf("seed cannot be nil")
	}

	if currentBeat < 0 {
		return nil, fmt.Errorf("invalid currentBeat: %d (must be >= 0)", currentBeat)
	}

	// Only active seeds can be harvested
	if seed.Status != SeedStatusActive {
		return nil, ErrSeedNotReady
	}

	// Calculate urgency (0-100 semantic score)
	urgency := seed.CalculateUrgency(currentBeat)

	// Convert to priority (0-500 system score) using simple scaling formula
	// This maintains compatibility with GlobalSeed priority range while ensuring
	// high-urgency LocalSeeds take precedence
	priority := urgency * 5

	// Extract keywords from Content (simple split on spaces, take first 3 words)
	keywords := extractKeywords(seed.Content)

	return &HarvestInstruction{
		SeedID:      seed.ID,
		ClueContent: seed.PlantText,
		Keywords:    keywords,
		MustInclude: seed.Detail, // Key detail that must be echoed
		Priority:    priority,
		Tier:        0,           // LocalSeeds don't have tiers
		IsLocalSeed: true,
	}, nil
}

// extractKeywords extracts keywords from content for narrative echoing.
// Implements simple keyword extraction by:
//  1. Splitting content by common punctuation (Chinese and English)
//  2. Filtering segments by length (2-10 characters for meaningful keywords)
//  3. Limiting to top 5 keywords to avoid overwhelming narration
//
// Parameters:
//   - content: The content string to extract keywords from
//
// Returns:
//   - []string: List of extracted keywords (empty if none found)
func extractKeywords(content string) []string {
	if content == "" {
		return []string{}
	}

	keywords := []string{}

	// Split by common Chinese and English punctuation
	var currentSegment string
	for _, r := range content {
		switch r {
		case '，', '。', '、', '！', '？', '；', '：', ',', '.', '!', '?', ';', ':', ' ':
			if currentSegment != "" {
				keywords = append(keywords, currentSegment)
				currentSegment = ""
			}
		default:
			currentSegment += string(r)
		}
	}

	// Add final segment if exists
	if currentSegment != "" {
		keywords = append(keywords, currentSegment)
	}

	// Filter by length: keep only 2-10 character segments
	filtered := make([]string, 0, len(keywords))
	for _, kw := range keywords {
		runeCount := len([]rune(kw))
		if runeCount >= 2 && runeCount <= 10 {
			filtered = append(filtered, kw)
		}
	}

	// Limit to 5 keywords max to prevent narrative overload
	if len(filtered) > 5 {
		filtered = filtered[:5]
	}

	return filtered
}
