#!/usr/bin/env python3
"""進度看板工具 — 從 dev/stories/*.md（工單）重算 dev/STATUS.md，並 lint 交叉引用。

工單(work order)為工作單位，分組依 stage（階段 0–7），標 lane（工線 A–F）。
STATUS.md 由工單 frontmatter 機械重算，非手寫——關機/context 缺失後跑 `board.py --check`
即可驗證無漂移、無懸空依賴、無前向依賴（depends_on 的 stage 不得大於自身）、in_progress 殘留。

用法:
  board.py            # 重算並寫入 dev/STATUS.md
  board.py --check    # 不寫檔；比對漂移 + lint，有漂移/錯誤回非 0（復原協定/CI 用）
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STORIES_DIR = ROOT / "dev" / "stories"
STATUS_MD = ROOT / "dev" / "STATUS.md"
CONTRACTS_MD = ROOT / "dev" / "CONTRACTS.md"

VALID_STATUS = ["todo", "in_progress", "blocked", "done"]
STATUS_ICON = {"todo": "⬜", "in_progress": "🟡", "blocked": "🟥", "done": "✅"}

LIST_FIELDS = {"depends_on", "contracts"}
SCALAR_FIELDS = {"id", "stage", "lane", "title", "status", "worktree",
                 "last_good_snapshot", "owner_session"}


def _natkey(s: str):
    """自然排序鍵：U2 排在 U10 之前；stage 數字正確排序。"""
    return [int(t) if t.isdigit() else t for t in re.findall(r"\d+|\D+", str(s))]


def _stage_num(s: dict):
    """取工單 stage 的數值。MVP-B 'B'→7、穩定化補丁 'S'→8、配置中心 'P'→9，依序排在 MVP-A 之後。"""
    v = str(s.get("stage", "")).strip().upper()
    if v.isdigit():
        return int(v)
    return {"B": 7, "S": 8, "P": 9, "N": 10, "C": 11, "R": 12, "H": 13}.get(v, 99)


# ── frontmatter 解析（不依賴 pyyaml）──────────────────────────────────────
def parse_frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end].strip("\n")
    data: dict = {}
    for line in block.splitlines():
        line = line.rstrip()
        if not line or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if " #" in val:
            val = val.split(" #", 1)[0].strip()
        if key in LIST_FIELDS:
            val = val.strip()
            if val in ("", "[]", "-"):
                data[key] = []
            else:
                data[key] = [x.strip() for x in val.strip("[]").split(",") if x.strip()]
        else:
            data[key] = val
    return data


def load_stories() -> list[dict]:
    out = []
    for f in sorted(STORIES_DIR.glob("*.md")):
        fm = parse_frontmatter(f.read_text(encoding="utf-8"))
        if fm.get("id"):
            fm["_file"] = f.name
            out.append(fm)
    return out


def load_contract_ids() -> set[str]:
    if not CONTRACTS_MD.exists():
        return set()
    ids: set[str] = set()
    for m in re.finditer(r"`([A-Za-z][\w./-]+)`", CONTRACTS_MD.read_text(encoding="utf-8")):
        ids.add(m.group(1))
    return ids


# ── STATUS.md 重算 ─────────────────────────────────────────────────────────
AUTO_BEGIN = "<!-- AUTO-GENERATED by dev/tools/board.py — 不要手改；改 stories/*.md 後重跑 -->"
AUTO_END = "<!-- END AUTO-GENERATED -->"
STAGE_TITLE = {
    "0": "階段 0 · 契約凍結 + 地基", "1": "階段 1 · 核心資料層（無 LLM）",
    "2": "階段 2 · LLM 基礎 + agent 外殼", "3": "階段 3 · 核心 agent 真接",
    "4": "階段 4 · story + compactor", "5": "階段 5 · beat 主迴圈",
    "6": "階段 6 · 前端 + MVP-A 打磨", "B": "MVP-B",
    "S": "階段 S · 穩定化補丁（Narrative Progress Kernel）",
    "P": "階段 P · 配置中心 / Story Agent 模組化（patch v1.1）",
    "N": "階段 N · 敘事控制（Narrative Control patch v0.1）",
    "C": "階段 C · MVP-C（聊天室 + 離場命運）",
    "R": "階段 R · 敘事控制 v0.2（揭露橋接 Revelation Bridge）",
    "H": "階段 H · Runtime Hard-Gate（v0.3.1 結局/揭露/NPC/品質硬閘）",
}


def render_status(stories: list[dict]) -> str:
    counts = {s: 0 for s in VALID_STATUS}
    for st in stories:
        counts[st.get("status", "todo")] = counts.get(st.get("status", "todo"), 0) + 1
    total = len(stories)
    done = counts.get("done", 0)
    pct = (done * 100 // total) if total else 0

    lines = [
        "# STATUS — 工單看板（唯一事實來源）",
        "",
        AUTO_BEGIN,
        "",
        f"**總計 {total} 個工單｜完成 {done}（{pct}%）｜"
        f"⬜ todo {counts['todo']}｜🟡 in_progress {counts['in_progress']}｜"
        f"🟥 blocked {counts['blocked']}｜✅ done {done}**",
        "",
        "> 本檔由 `python dev/tools/board.py` 從 `dev/stories/*.md`（工單）重算。",
        "> 不要手改本區塊。改工單 frontmatter 後重跑 board.py。",
        "> 開機請先跑 `board.py --check`（見 dev/ROLLBACK.md）。施工方法見 dev/PARALLEL-PLAN.md。",
        "",
    ]

    hot = sorted([s for s in stories if s.get("status") in ("in_progress", "blocked")],
                 key=lambda s: _natkey(s["id"]))
    if hot:
        lines += ["## ⚠ 需注意（in_progress / blocked）— 復原時優先處理", "",
                  "| 工單 | 狀態 | stage | lane | worktree | owner_session | 最後 known-good |",
                  "|---|---|---|---|---|---|---|"]
        for s in hot:
            lines.append(
                f"| {s['id']} {s.get('title','')} | {STATUS_ICON.get(s.get('status'),'')} {s.get('status')} "
                f"| {s.get('stage','-')} | {s.get('lane','-')} | {s.get('worktree','-')} "
                f"| {s.get('owner_session','-')} | {s.get('last_good_snapshot','-')} |")
        lines.append("")

    by_stage: dict[str, list[dict]] = {}
    for s in stories:
        by_stage.setdefault(str(s.get("stage", "?")), []).append(s)

    lines += ["## 依階段", ""]
    for stage in sorted(by_stage, key=lambda x: _stage_num({"stage": x})):
        grp = by_stage[stage]
        d = sum(1 for s in grp if s.get("status") == "done")
        title = STAGE_TITLE.get(stage, f"階段 {stage}")
        lines += [f"### {title}（{d}/{len(grp)}）", "",
                  "| 工單 | 狀態 | lane | depends_on | contracts | known-good |",
                  "|---|---|---|---|---|---|"]
        for s in sorted(grp, key=lambda x: _natkey(x["id"])):
            lines.append(
                f"| **{s['id']}** {s.get('title','')} "
                f"| {STATUS_ICON.get(s.get('status'),'')} {s.get('status','todo')} "
                f"| {s.get('lane','-')} "
                f"| {', '.join(s.get('depends_on', [])) or '-'} "
                f"| {', '.join(s.get('contracts', [])) or '-'} "
                f"| {s.get('last_good_snapshot','-')} |")
        lines.append("")

    lines += [AUTO_END, ""]
    return "\n".join(lines)


# ── lint ───────────────────────────────────────────────────────────────────
def lint(stories: list[dict]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warns: list[str] = []
    ids = [s["id"] for s in stories]
    idset = set(ids)
    stage_of = {s["id"]: _stage_num(s) for s in stories}
    contract_ids = load_contract_ids()

    parsed_files = {s.get("_file") for s in stories}
    for f in sorted(STORIES_DIR.glob("*.md")):
        if f.name not in parsed_files:
            errors.append(f"工單檔 {f.name} 解析不到 id（frontmatter 壞了或被截斷？）")

    for d in sorted({i for i in ids if ids.count(i) > 1}):
        errors.append(f"重複的工單 id: {d}")

    for s in stories:
        sid = s["id"]
        if s.get("status") not in VALID_STATUS:
            errors.append(f"{sid}: 不合法 status {s.get('status')!r}")
        for dep in s.get("depends_on", []):
            if dep not in idset:
                errors.append(f"{sid}: depends_on 指向不存在的工單 {dep}")
            elif stage_of.get(dep, 99) > stage_of.get(sid, 0):
                errors.append(f"前向依賴! {sid}(階段{stage_of[sid]}) 依賴 "
                              f"{dep}(階段{stage_of[dep]})")
        if contract_ids:
            for c in s.get("contracts", []):
                if c not in contract_ids:
                    warns.append(f"{sid}: contract {c!r} 不在 CONTRACTS.md")
        if s.get("status") == "in_progress":
            if s.get("owner_session", "-") in ("-", ""):
                warns.append(f"{sid}: in_progress 但無 owner_session（防雙寫應填）")
            if s.get("worktree", "-") in ("-", ""):
                warns.append(f"{sid}: in_progress 但無 worktree")
        if s.get("status") == "done" and s.get("last_good_snapshot", "-") in ("-", ""):
            warns.append(f"{sid}: done 但無 last_good_snapshot（Definition of Done 要求 post 快照）")
    return errors, warns


# ── main ───────────────────────────────────────────────────────────────────
def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="從 stories/*.md（工單）重算 STATUS.md 並 lint")
    ap.add_argument("--check", action="store_true",
                    help="不寫檔；比對 STATUS.md 漂移 + lint，有問題回非 0")
    args = ap.parse_args(argv)

    if not STORIES_DIR.exists():
        print(f"ERROR: 找不到 {STORIES_DIR}", file=sys.stderr)
        return 2
    stories = load_stories()
    rendered = render_status(stories)
    errors, warns = lint(stories)

    if args.check:
        drift = False
        if not STATUS_MD.exists():
            print("DRIFT: STATUS.md 不存在（請先跑不帶 --check 的 board.py 生成）")
            drift = True
        elif STATUS_MD.read_text(encoding="utf-8") != rendered:
            print("DRIFT: STATUS.md 與 stories/*.md 重算結果不一致（有人手改？跑 board.py 重生）")
            drift = True
        else:
            print("OK: STATUS.md 與 stories/*.md 一致")
        for w in warns:
            print(f"WARN: {w}")
        for e in errors:
            print(f"ERROR: {e}")
        print(f"--- {len(stories)} 工單, {len(errors)} errors, {len(warns)} warns ---")
        return 1 if (drift or errors) else 0

    STATUS_MD.write_text(rendered, encoding="utf-8")
    print(f"OK 寫入 {STATUS_MD.relative_to(ROOT)}（{len(stories)} 工單）")
    for w in warns:
        print(f"WARN: {w}")
    for e in errors:
        print(f"ERROR: {e}")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
