package chat

import (
	"github.com/nightmare-assault/nightmare-assault/internal/npc/knowledge"
	"github.com/nightmare-assault/nightmare-assault/internal/npc/manager"
)

// ChatFlag represents semantic properties detected by JudgeAgent during chat analysis.
// These flags indicate potentially important player behaviors that affect NPC responses.
// This is a local definition to avoid import cycles with views package.
type ChatFlag string

const (
	// ChatFlagHallucination indicates the player is claiming something that didn't happen
	ChatFlagHallucination ChatFlag = "hallucination"

	// ChatFlagHostile indicates aggressive or threatening language
	ChatFlagHostile ChatFlag = "hostile"

	// ChatFlagRevelation indicates sharing important information or secrets
	ChatFlagRevelation ChatFlag = "revelation"

	// ChatFlagPersuasion indicates attempting to convince or manipulate
	ChatFlagPersuasion ChatFlag = "persuasion"

	// ChatFlagLie indicates the player is deliberately lying
	ChatFlagLie ChatFlag = "lie"

	// ChatFlagContradiction indicates information contradicting what NPC knows
	ChatFlagContradiction ChatFlag = "contradiction"
)

// String returns the string representation of ChatFlag.
func (f ChatFlag) String() string {
	return string(f)
}

// ParseChatFlag converts a string to ChatFlag.
// Returns the flag and true if valid, or ChatFlagHallucination and false if invalid.
func ParseChatFlag(s string) (ChatFlag, bool) {
	switch s {
	case "hallucination":
		return ChatFlagHallucination, true
	case "hostile":
		return ChatFlagHostile, true
	case "revelation":
		return ChatFlagRevelation, true
	case "persuasion":
		return ChatFlagPersuasion, true
	case "lie":
		return ChatFlagLie, true
	case "contradiction":
		return ChatFlagContradiction, true
	default:
		return ChatFlagHallucination, false
	}
}

// ProcessResult is the result of processing a player's chat message
// This structure is the integration point between Story 4-2, 4-6, and 4-7
type ProcessResult struct {
	// NPCResponses contains all NPC responses generated (Story 4-4)
	NPCResponses []NPCResponse

	// EmotionChanges maps NPCID to emotion delta applied (Story 4-6)
	EmotionChanges map[string]manager.EmotionDelta

	// Flags contains all chat flags detected by JudgeAgent (Story 4-1)
	Flags []ChatFlag

	// Contradictions contains all contradictions detected (Story 4-7)
	Contradictions []knowledge.ContradictionResult

	// Success indicates if processing completed successfully
	Success bool

	// Error contains error message if processing failed
	Error string
}

// NPCResponse represents a single NPC's response to the player's message
// Generated by Story 4-4 (NPC Response Generation)
type NPCResponse struct {
	// NPCID is the unique identifier of the responding NPC
	NPCID string

	// Content is the generated response text
	Content string

	// Emotion is the NPC's emotional state when responding
	Emotion manager.EmotionState

	// Flags are any special flags associated with this response
	Flags []ChatFlag

	// UsedFallback indicates if this response used a fallback template (Story 4-5)
	UsedFallback bool
}

// ChatSession represents an ongoing chat conversation
// Used by Story 4-2 (ChatProcessor)
type ChatSession struct {
	// SessionID uniquely identifies this chat session
	SessionID string

	// Participants lists all NPCs and player in this session
	Participants []ChatParticipant

	// Location is the current room/scene where chat is happening
	Location string

	// MessageHistory contains recent chat messages
	MessageHistory []ChatMessage

	// MaxHistoryLength limits how many messages to keep
	MaxHistoryLength int
}

// ChatParticipant represents a participant in the chat
// Defined for Story 4-1 but used across all chat stories
type ChatParticipant struct {
	// ID is the participant identifier (npcID or "player")
	ID string

	// Name is the display name
	Name string

	// IsPlayer indicates if this is the player
	IsPlayer bool

	// Emotion is the current emotional state (only for NPCs)
	Emotion manager.EmotionState

	// Relationship is the relationship status with player
	Relationship string
}

// ChatMessage represents a single message in the conversation
// Used for conversation history in Story 4-1 and 4-2
type ChatMessage struct {
	// SenderID is who sent this message
	SenderID string

	// Content is the message text
	Content string

	// Timestamp when message was sent
	Timestamp int

	// Flags associated with this message (from JudgeAgent)
	Flags []ChatFlag
}
